runtime: aspnetcore
env: flex

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
  
entrypoint: dotnet run --project src/Volunteasy.Api/Volunteasy.Api.csproj
  
env_variables:
  ASPNETCORE_ENVIRONMENT: Staging