version: '3.3'
services:
  govobs:
    container_name: "govobs"
    build:
      context: '.'
      dockerfile: ./deploy/dev/Dockerfile
    restart: unless-stopped
    environment:
      APP_NAME: govobs
      ENVIRONMENT: production
      API_PORT: 8080
      MYSQL_DSN: voifftbvfkvxmg2mzna4:pscale_pw_SHSU3bLhT9luwUGH4KlqIuG8aSkMTmfdfO7IpNFKdTX@tcp(aws-sa-east-1.connect.psdb.cloud)/volunteasy?tls=true
    ports:
      - "8080:8080"