version: '3.3'
services:
  govobs:
    container_name: "govobs"
    build:
      context: '.'
      dockerfile: ./deploy/dev/Dockerfile
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      APP_NAME: govobs
      ENVIRONMENT: production
      API_PORT: 8080
    ports:
      - "8080:8080"