version: '3.3'
services:
  api:
    build:
      context: '.'
      dockerfile: ./deploy/dev/Dockerfile
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      APP_NAME: govobs
      ENVIRONMENT: production
      API_PORT: 8080
    ports:
      - "80:8080"
  obs:
    image: timberio/vector:0.28.1-alpine
    command: --config /vector.toml
    volumes:
      - ${PWD}/vector.toml:/vector.toml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock