version: '3.3'
services:
  govobs_database:
    image: mysql:8.0
    restart: always
    container_name: govobs_local_db
    environment:
      MYSQL_DATABASE: 'volunteasy'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'volunteasy'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'volunteasy'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'volunteasy'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - govobs-db:/var/lib/mysql
# Names our volume
volumes:
  govobs-db: