server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://414905:eyJrIjoiNjVkN2ZhNWI3YzE3MDM5NGE0OTI1NmRiMDNiMjBlNTI5OTExMWJiNyIsIm4iOiJsb2tpLWxvZ3MtZ292b2JzIiwiaWQiOjgxNzAxN30=@logs-prod-015.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log