name: Build

on:
    push:
        branches: [ main ]
        
    pull_request:
        
concurrency:
    group: pull-request-${{ github.head_ref }}
    cancel-in-progress: true

jobs:

build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
              go-version: 1.19

        - name: Build
          run: make

        - name: Test
          run: make test