name: Build

on:
  push:
    branches: [main]

concurrency:
  group: push-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build
        run: make

      - name: Test
        run: make test

      - name: Prepare environment
        run: cp deploy/dev/docker-compose.yaml -t .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: volunteasy
          environment_name: volunteasy-dev
          version_label: ${{github.SHA}}
          region: sa-east-1
          version_description: ${{github.SHA}}
          deployment_package: deploy.zip

  test:
    name: Test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Run tests
        run: make test

  check_generated:
    name: Check generated code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Check generated code
        run: |
          make gen
          git diff --exit-code --ignore-space-change

  deploy:
    name: Deploy to Beanstalk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build
        run: make

      - name: Prepare environment
        run: |
          cp deploy/dev/docker-compose.yaml -t .
          zip -r deploy.zip . -x '*.git*'=

      - name: Deploy artifact
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: volunteasy
          environment_name: volunteasy-dev
          version_label: ${{github.SHA}}
          region: sa-east-1
          version_description: ${{github.SHA}}
          deployment_package: deploy.zip