name: Build

on:
    push:
        branches: [ main ]

concurrency:
    group: pull-request-${{ github.head_ref }}
    cancel-in-progress: true

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20

            - name: Build
              run: make

            - name: Test
              run: make test

            - name: Prepare environment
              run: cp deploy/dev/docker-compose.yaml -t .

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v21
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: volunteasy
                  environment_name: volunteasy-dev
                  version_label: ${{github.SHA}}
                  region: sa-east-1
                  version_description: ${{github.SHA}}
                  deployment_package: deploy.zip

