name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: push-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to dev environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: volunteasy

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud auth configure-docker gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/volunteasy-dev:${{ github.sha }} .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/volunteasy-dev:${{ github.sha }}

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --image-url=gcr.io/${{ secrets.PROJECT_ID }}/your-image-name:${{ github.sha }} --quiet