name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: push-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to dev environment
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          deliverables: 'deploy/dev/app.yaml'