name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: push-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to dev environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push API Docker image
        run: |
          mv ./build/Dockerfile .
          export IMAGE_NAME=gcr.io/volunteasy-392610/dev/api:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          
      - name: Deploy API to Google Cloud Run
        run: |
            gcloud run deploy volunteasy-dev --image=gcr.io/volunteasy-392610/dev/api:${{ github.sha }} --platform=managed --region=southamerica-east1
            gcloud run services update-traffic volunteasy-dev --to-latest --region=southamerica-east1
          
      - name: Build and push Web Docker image
        run: |
          mv ./build/Dockerfile .
          export IMAGE_NAME=gcr.io/volunteasy-392610/dev/web:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy Web to Google Cloud Run
        run: |
          gcloud run deploy volunteasy-web-dev --image=gcr.io/volunteasy-392610/dev/web:${{ github.sha }} --platform=managed --region=southamerica-east1
          gcloud run services update-traffic volunteasy-web-dev --to-latest --region=southamerica-east1