name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: push-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to dev environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          cache: true

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Prepare environment
        run: |
          mv deploy/dev/docker-compose.yaml -t .
          zip -r deploy.zip .

      - name: Deploy artifact
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: volunteasy
          environment_name: volunteasy-dev
          version_label: ${{github.SHA}}
          region: sa-east-1
          version_description: ${{github.SHA}}
          deployment_package: deploy.zip